### ISSUE TITLE
Add Support for Spark SQL

### ISSUE THREAD

**Issue by fuyufjh** [apache/rocketmq-externals#71] opened 2018-06-22 08:23 UTC
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently RocketMQ already supports Spark RDD API as well as D-Stream. It would be nice if it also supports Spark SQL and Spark Structured Streaming.

By the way, the Spark SQL's API is very different from Spark's, so it's almost impossible if you need to integrate with Spark SQL or Structured Streaming.

2. Provide any additional detail on your proposed use case for this feature.

I want to use Spark SQL / Spark Structured Streaming with RocketMQ.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

I don't think there is a clear solution or workaround. As I described in part 1, it's almost impossible to use Structured Streaming with RocketMQ.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

We may decompose the task into following sub-tasks, referred to the source code of [spark-sql-kafka-0-10](https://github.com/apache/spark/tree/master/external/kafka-0-10-sql).

* RocketMQStreamSourceProvider
* RocketMQRelationProvider
* RocketMQStreamSinkProvider
* RocketMQCreatableRelationProvider
* RocketMQStreamWriteSupport
* RocketMQContinuousReadSupport

**Comment by vongosling** [comment] 2018-06-26 13:32
@vesense How do you think about if we hope to integrate with Spark Structured Streaming

**Comment by vongosling** [comment] 2018-08-07 02:38
I have merged the pr.

**Closed by vongosling** 2018-08-07 02:38 UTC
Labels: enhancement

**Comment by hengyuan** [comment] 2018-08-08 04:05
Caused by: java.lang.IllegalArgumentException: Option 'group' can not be specified

**Comment by hengyuan** [comment] 2018-08-08 04:06
val df = spark
      .readStream
      .format("org.apache.spark.sql.rocketmq.RocketMQSourceProvider")
      .option("nameServer", "192.168.2.210:9876;192.168.2.211:9876")
      .option("topic", "testtopic")
      .option("group","streaming1")
      .load()
Caused by: java.lang.IllegalArgumentException: Option 'group' can not be specified
